services:
  mssql-2019:
    build:
      context: docker/
      dockerfile: docker-mssql-2019.dockerfile
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    ports:
      - "1433:1433"